version: '3.9'
services:
  app:
    image: vitaliimadiakin/robert:$GITHUB_RUN_ID
    container_name: robert_app
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      TOKEN: ${TOKEN}
      AMPLITUDE_API_KEY: ${AMPLITUDE_API_KEY}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}

  postgres:
    container_name: robert_pg
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
